---
containers:
  - name: stage1
    ipv4_address: 10.0.10.10
    image: images:debian/buster/cloud
    type: lxd
  - name: stage2
    ipv4_address: 10.0.10.11
    image: images:debian/buster/cloud
    type: lxd
