---
- name: Adapt SSH client configuration
  copy:
    src: ssh_config.conf
    dest: /etc/ssh/ssh_config.d/training.conf
    owner: root

- name: Create /etc/hosts records
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ipv4_address }} {{ item.name }}"
  loop: "{{ containers }}"
  when: containers is defined

- name: Block access to remote docker daemons
  iptables:
    chain: OUTPUT
    protocol: tcp
    destination_port: "2375"
    jump: DROP
