---
- name: Install the LXD package
  apt:
    name: lxd
    state: present
    update_cache: yes
  register: lxd_daemon

- name: Initialize LXD
  vars:
    lxd_conf: "{{ lookup('template', 'configuration.yml') }}"
  shell:
    cmd: lxd init --preseed
    stdin: "{{ lxd_conf }}"
  when: lxd_daemon.changed
