---

- hosts: all
  become: yes

  vars_files:
    - "vars/root_ssh_keys.yml"
    - "vars/training_network.yml"

  pre_tasks:
    - name: Debian 10 required
      assert:
        that:
          - ansible_distribution == "Debian"
          - ansible_distribution_major_version == "10"
        msg: "Debian 10 is required"

    - name: Install dependencies, avoid a warning
      raw: "{{ item }}"
      loop:
        - apt-get update
        - apt-get -y install python3-apt

  roles:

    - role: common

    - role: docker

    - role: users
      vars:
        users: 
          - name: "training"
            passwd: "strudl"
            ssh_key: "{{ lookup('file', 'ssh/user.pub') }}"
            groups: "docker"
