---

- hosts: all
  become: yes

  vars_files:
    - "vars/root_ssh_keys.yml"
    - "vars/training_network.yml"
    - "vars/training_nodes.yml"

  tasks:
    - name: Adapt SSH client configuration
      copy:
        src: ssh_config.conf
        dest: /etc/ssh/ssh_config.d/training.conf
        owner: root

    - name: Create /etc/hosts records
      lineinfile:
        path: /etc/hosts
        line: "{{ item.ipv4_address }} {{ item.name }}"
      loop: "{{ containers }}"


  roles:
    - role: common

    - role: docker
      vars:
        image: ubuntu-egi2020

    - role: users
      vars:
        users: 
          - name: "training"
            passwd: "20202020"
            ssh_priv_key_path: "ssh/user"
            groups: "docker"

    - role: docker-containers
