---

- hosts: all
  become: yes

  vars_files:
    - "vars/root_ssh_keys.yml"
    - "vars/training_network.yml"
    - "vars/training_nodes.yml"

  roles:
    - role: common

    - role: docker
      vars:
        image: ubuntu-egi2020

    - role: users
      vars:
        users: 
          - name: "training"
            passwd: "20202020"
            ssh_priv_key_path: "ssh/user"
            groups: "docker"

    # just to make sure it runs before containers
    - role: training

    - role: docker-containers
