---

- hosts: all
  become_method: sudo
  become: yes

  vars_files:
    - "vars/root_ssh_keys.yml"
    - "vars/training_network.yml"

  tasks:
    - name: Prepare Ansible playbook for the second stage
      copy:
        src: ../../deployment
        dest: /root
        owner: root

    - name: Install Ansible
      apt:
        name: ansible
        update_cache: yes

  roles:
    - role: common

    - role: users
      vars:
        users: 
          - name: "training"
            passwd: "strudl"
            ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAyVFeFqVtCp0K/OxJZmBciW4NZnTM6flt2Fh7/iucRZERZkPMIJtvFlsIJTIj+79AVw1jYqVOvgOrpynOn/h3c8rfvEL96scI+xR+4BXUkijmYC7ldrBGzzOqlfWVhxHwPlc0xWXHLcEMdwBkdcQ3AFilK6M+PdFo0Ma+P8FQECCYzrmXAn9aUq0kyfn0qr49O6+U2mUiUJSaupG1C+kjcjpC0UE/5jp0ckFPKyrZ9uwNjpFMBigLRyroUiYDuXPxF7LQ2oP8U2jKC/9MZFOXyWPb/OkhsNV6KLH8WoTLNCynmNOGa02b5SyujypD6vLAUO327AZ6a/Byg0iN4OHEuw== kouril@ics.muni.cz"

    - role: lxd
    - role: lxd-container
      vars:
        containers:
          - name: stage1
            ipv4_address: 10.0.10.10
            image: images:debian/buster/cloud
          - name: stage2
            ipv4_address: 10.0.10.11
            image: images:debian/buster/cloud
