---

- name: Prepare the main host
  hosts: main
  become: yes

  vars_files:
    - "vars/root_ssh_keys.yml"
    - "vars/training_network.yml"

  roles:
    - role: common
      vars:
        hostname: "main"

    - role: docker

    - role: users
      vars:
        users: 
          - name: "training"
            passwd: "20202020"
            ssh_priv_key_path: "ssh/user"
            groups: "docker"
          - name: "david"
            passwd: "rekcod"

    # just to make sure it runs before containers
    - role: training

- name: Prepare the secondary host
  hosts: jenkins_runner
  become: yes

  vars_files:
    - "vars/root_ssh_keys.yml"
    - "vars/training_network.yml"

  roles:
    - role: common
      vars:
        hostname: jenkins-runner

    - role: docker
      vars:
        expose_docker: yes

    - role: training
      vars:
        docker_server: "10.0.10.1"

    - role: docker-containers
      vars:
        containers:
            # cgroups should be started first, to make sure (?) it's listed first in the mounts (needed to pass)
          - name: cgroups
            ipv4_address: 10.0.10.10
            launch: docker run --rm -d --network=training_network --ip 10.0.10.10 --name cgroups --hostname cgroups --cap-add=SYS_ADMIN --security-opt apparmor=unconfined -v /root/tasks/ssh/:/root/.ssh -p 62222:22 rastasheep/ubuntu-sshd:18.04 /usr/sbin/sshd -D
            type: docker
          - name: jenkins-dev
            launch: docker run --rm -d --network=training_network --name jenkins-dev --hostname jenkins-dev -v /root/tasks/ssh/:/root/.ssh -v /root/tasks/etc/jenkins:/etc/jenkins -p 2222:22 rastasheep/ubuntu-sshd:18.04 /usr/sbin/sshd -D
            type: docker
