---

- name: Prepare the main host
  hosts: main
  become: yes

  vars_files:
    - "vars/root_ssh_keys.yml"
    - "vars/training_network.yml"
    - "vars/task3.yml"

  roles:
    - role: common
      vars:
        hostname: "main"

    - role: docker

    - role: users
      vars:
        users: 
          - name: "training"
            passwd: "20202020"
            ssh_priv_key_path: "ssh/user"
          - name: "{{ task3_username }}"
            passwd: "{{ task3_password }}"
            groups: "docker"

    # just to make sure it runs before containers
    - role: training
      vars:
        docker_server: "10.20.30.49"

    - role: docker-containers
      vars:
        containers:
          - name: task1
            ipv4_address: 10.0.10.10
            launch: docker run --rm -d --network=training_network --ip 10.0.10.10 --name task1 --cap-add=SYS_ADMIN --security-opt apparmor=unconfined -v /root/task2/ssh/:/root/.ssh rastasheep/ubuntu-sshd:18.04 /usr/sbin/sshd -D
            type: docker

- name: Prepare the secondary host
  hosts: remote_docker
  become: yes

  vars_files:
    - "vars/root_ssh_keys.yml"
    - "vars/training_network.yml"
    - "vars/task3.yml"

  tasks:
    - name: Docker probe
      template:
        src: docker_probe.j2
        dest: /usr/local/sbin/docker_probe
        owner: root
        mode: 0700

  roles:
    - role: common
      vars:
        hostname: jenkins-runner

    - role: docker
      vars:
        expose_docker: yes
