---
- name: Enable password authentication for SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: ^ChallengeResponseAuthentication
    line: ChallengeResponseAuthentication yes

- name: Add system users
  user:
    name: "{{ item.name }}"
    password: "{{ item.passwd  | password_hash('sha512') }}"
    shell: "/bin/bash"
    state: present
  loop: "{{ users }}"

- name: Add SSH for users
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.ssh_key }}"
  loop: "{{ users }}"
