---
- name: Enable password authentication for SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: ^ChallengeResponseAuthentication
    line: ChallengeResponseAuthentication yes

- include_tasks: create_user.yml
  loop: "{{ users }}"
