---
- name: "Create custom fact directory"
  file:
    path: "/etc/ansible/facts.d"
    state: "directory"

- name: "Insert custom fact file to check LXC containers"
  copy:
    src: lxc.fact
    dest: /etc/ansible/facts.d/lxc.fact
    mode: 0755

- name: Reload ansible_local
  setup: filter=ansible_local

- name: Create a container
  shell:
    cmd: lxc launch {{ item.image }} {{ item.name }}
    stdin: "{{ lookup('template', 'container-config.yml') }}"
# when: not {{ item.name }} in ... -> yeilds a warning about jinja2 templating used
  when:
    - not item.name|string in ansible_facts['ansible_local']['lxc']['containers']
    - item.type == "lxd"
  loop: "{{ containers }}"

- name: Create /etc/hosts records
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ipv4_address }} {{ item.name }}"
  loop: "{{ containers }}"

#- name: Create a container
#  vars:
#     lxcconfig: "{{ lookup('template', 'container-config.yml') }}"
#  community.general.lxd_container:
#    name: "{{ item.name }}"
#    state: started
#    config: "{{ lxcconfig }}"
#    source:
#      type: image
#      mode: pull
#      server: https://images.linuxcontainers.org
#      protocol: lxd # if you get a 404, try setting protocol: simplestreams
#      alias: ubuntu/xenial/amd64
#  when: not item.name|string in ansible_facts['ansible_local']['lxc']['containers']
## when: not {{ item.name }} in ... -> yeilds a warning about jinja2 templating used
#  loop: "{{ containers }}"
