---
- name: set timezone to Europe/Prague
  timezone:
    name: Europe/Prague

- name: Set SSH keys for root
  authorized_key:
    user: root
    state: present
    key: "{{ item }}"
  loop: "{{ root_ssh_keys }}"
